before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -X aws-sso-creds-default-login/pkg/version.Version={{.Version}}
  binary: aws-sso-creds
  main: ./cmd/aws-sso-creds/main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  - 
    name: aws-sso-creds
    tap:
      owner: alecuba16
      name: homebrew-tap
    commit_author:
      name: Alejandro Blanco-M
      email: alecuba16@gmail.com
    folder: Formula
    homepage: "https://www.linkedin.com/in/alejandro-blanco-m-b847244b/"
    description: "Get AWS SSO temporary creds from an SSO profile. Includes set as the default profile inside the credentials and login flag"
